--------------------------------------------------------
--  File created - Friday-December-09-2022   
--------------------------------------------------------
DROP TABLE "SYSTEM"."NUTRITIONIST";
--------------------------------------------------------
--  DDL for Table NUTRITIONIST
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."NUTRITIONIST" 
   (	"N_ID" VARCHAR2(10 BYTE), 
	"FIRST_NAME" VARCHAR2(20 BYTE), 
	"LAST_NAME" VARCHAR2(20 BYTE), 
	"EMAIL" VARCHAR2(50 BYTE), 
	"GENDER" VARCHAR2(20 BYTE), 
	"PASSWORD" VARCHAR2(30 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYSTEM.NUTRITIONIST
SET DEFINE OFF;
Insert into SYSTEM.NUTRITIONIST (N_ID,FIRST_NAME,LAST_NAME,EMAIL,GENDER,PASSWORD) values ('111','Bhola','Baba','Bhola@gmail.com','Male','Bhola1');
Insert into SYSTEM.NUTRITIONIST (N_ID,FIRST_NAME,LAST_NAME,EMAIL,GENDER,PASSWORD) values ('23','Anita','Bose','ABose@gmail.com','Female','AB@123');
Insert into SYSTEM.NUTRITIONIST (N_ID,FIRST_NAME,LAST_NAME,EMAIL,GENDER,PASSWORD) values ('1','Pranita','Sutar','pranita@gmnail.com','Female','Pranita@123');
Insert into SYSTEM.NUTRITIONIST (N_ID,FIRST_NAME,LAST_NAME,EMAIL,GENDER,PASSWORD) values ('2','Rahul','Poojari','rahul@gmnail.com','Male','Rahul@123');
Insert into SYSTEM.NUTRITIONIST (N_ID,FIRST_NAME,LAST_NAME,EMAIL,GENDER,PASSWORD) values ('3','Antara','Bhatt','antara@gmnail.com','Female','Antara@123');
Insert into SYSTEM.NUTRITIONIST (N_ID,FIRST_NAME,LAST_NAME,EMAIL,GENDER,PASSWORD) values ('4','Aditya','Lodha','aditya@gmnail.com','Male','Aditya@123');
Insert into SYSTEM.NUTRITIONIST (N_ID,FIRST_NAME,LAST_NAME,EMAIL,GENDER,PASSWORD) values ('5','Sagar','Chitre','sagar@gmnail.com','Male','Sagar@123');
--------------------------------------------------------
--  DDL for Index SYS_C008345
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C008345" ON "SYSTEM"."NUTRITIONIST" ("N_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table NUTRITIONIST
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."NUTRITIONIST" MODIFY ("FIRST_NAME" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."NUTRITIONIST" MODIFY ("LAST_NAME" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."NUTRITIONIST" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."NUTRITIONIST" MODIFY ("GENDER" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."NUTRITIONIST" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."NUTRITIONIST" ADD PRIMARY KEY ("N_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
