--------------------------------------------------------
--  File created - Friday-December-09-2022   
--------------------------------------------------------
DROP TABLE "SYSTEM"."PHYSICAL_ACTIVITY";
--------------------------------------------------------
--  DDL for Table PHYSICAL_ACTIVITY
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."PHYSICAL_ACTIVITY" 
   (	"ACTIVITY_ID" VARCHAR2(10 BYTE), 
	"TYPE" VARCHAR2(50 BYTE), 
	"USER_ID" VARCHAR2(50 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYSTEM.PHYSICAL_ACTIVITY
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index SYS_C008369
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C008369" ON "SYSTEM"."PHYSICAL_ACTIVITY" ("ACTIVITY_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table PHYSICAL_ACTIVITY
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."PHYSICAL_ACTIVITY" MODIFY ("TYPE" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."PHYSICAL_ACTIVITY" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."PHYSICAL_ACTIVITY" ADD PRIMARY KEY ("ACTIVITY_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PHYSICAL_ACTIVITY
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."PHYSICAL_ACTIVITY" ADD FOREIGN KEY ("USER_ID")
	  REFERENCES "SYSTEM"."USERS" ("USER_ID") ON DELETE CASCADE ENABLE;
